final products =  [
    {
     'id': '0',
     'title': 'Men\'s Adidas Shoes',
     'price': 55.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/adidas-blue_white.png',
     'Company': 'Adidas',
    },
     {
     'id': '1',
     'title': 'Adidas running Shoes',
     'price': 57.49,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/adidas-purple.png',
     'Company': 'Adidas',
    },
     {
     'id': '2',
     'title': 'Men\'s Adidas fashion Shoes',
     'price': 55.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/adidas-yellow.png',
     'Company': 'Adidas',
    },
    {
     'id': '3',
     'title': 'Nike basketball Shoes',
     'price': 45.69,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/nike-ash.png',
     'Company': 'Nike',
    },
    {
     'id': '4',
     'title': 'Nike running Shoes',
     'price': 40.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/nike-black_red.png',
     'Company': 'Nike',
    },
    {
     'id': '5',
     'title': 'Men\'s Nike running Shoes',
     'price': 55.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/nike-bluey.png',
     'Company': 'Nike',
    },
    {
     'id': '6',
     'title': 'Nike fashion Shoes',
     'price': 56.79,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/nike-red.png',
     'Company': 'Nike',
    },
    {
     'id': '7',
     'title': 'Nike Air max Shoes',
     'price': 43.59,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/nike-white.png',
     'Company': 'Nike',
    },
    {
     'id': '8',
     'title': 'Men\'s Reebok fashion Shoes',
     'price': 53.29,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/reebok-america.png',
     'Company': 'Reebok',
    },
    {
     'id': '9',
     'title': 'Reebok running Shoes',
     'price': 54.69,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/reebok-black.png',
     'Company': 'Reebok',
    },
    {
     'id': '10',
     'title': 'Men\'s Reebok fashion Shoes',
     'price': 42.19,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/reebok-multi.png',
     'Company': 'Reebok',
    },
     {
     'id': '11',
     'title': 'Reebok runing Shoes',
     'price': 33.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/reebok-orange.png',
     'Company': 'Reebok',
    },
     {
     'id': '12',
     'title': 'Men\'s Reebok Shoes',
     'price': 50.09,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/reebok-red_black.png',
     'Company': 'Reebok',
    },
     {
     'id': '13',
     'title': 'Men\'s Vance Shoes',
     'price': 45.99,
     'sizes': [8, 9, 10, 11],
     'imageUrl': 'assets/images/vance.png',
     'Company': 'Vance',
    },
];

final cart = [
    {
    'id': '3',
    'title': 'Nike Basketball Shoes',
    'price': 45.69,
    'imageUrl': 'assets/images/nike-ash.png',
    'company': 'Nike',
    'size': 9,
    },
];